Repository QwikDev/qwik, pull requests merged in 2024-11, with the labels that each got.

#7040 v2: make optimizer async + remove fs
  Cargo.lock
  Cargo.toml
  packages/docs/src/routes/api/qwik-optimizer/api.json
  packages/docs/src/routes/api/qwik-optimizer/index.md
  packages/qwik/src/napi/Cargo.toml
  packages/qwik/src/napi/src/lib.rs
  packages/qwik/src/optimizer/cli/Cargo.toml
  packages/qwik/src/optimizer/cli/src/main.rs
  packages/qwik/src/optimizer/core/Cargo.toml
  packages/qwik/src/optimizer/core/src/lib.rs
  packages/qwik/src/optimizer/core/src/package_json.rs
  packages/qwik/src/optimizer/core/src/parse.rs
  packages/qwik/src/optimizer/src/api.md
  packages/qwik/src/optimizer/src/index.ts
  packages/qwik/src/optimizer/src/optimizer.ts
  packages/qwik/src/optimizer/src/platform.ts
  packages/qwik/src/optimizer/src/plugins/plugin.ts
  packages/qwik/src/optimizer/src/types.ts
Labels: COMP: optimizer, STATUS-2: PR waiting for review

#7043 feat(v2): add nesting error file location
  packages/qwik/src/core/shared/utils/markers.ts
  packages/qwik/src/core/ssr/ssr-render-jsx.ts
  packages/qwik/src/core/ssr/ssr-types.ts
  packages/qwik/src/core/tests/container.spec.tsx
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#6991 fix: solve issue with Cache-Control header deletion
  .changeset/moaning-master-chief.md
  packages/qwik-city/src/middleware/request-handler/request-event.ts
Labels: COMP: DX, STATUS-2: requires discussion

#7053 feat: add max count retries on promise throw
  packages/qwik/src/core/shared/component-execution.ts
  packages/qwik/src/core/shared/utils/promises.ts
  packages/qwik/src/qwikloader.ts
Labels: VERSION: upcoming major

#7055 chore(v2): add short changelog of major changes for the next upcoming version
  .changeset/fresh-rocks-exercise.md
  .changeset/hip-hornets-cheer.md
  .changeset/sour-zebras-tell.md
  .changeset/sweet-socks-whisper.md
  .changeset/wild-cooks-pay.md
Labels: VERSION: upcoming major

#7057 fix: calling component as a function
  packages/qwik/src/core/shared/component.public.ts
  packages/qwik/src/core/tests/inline-component.spec.tsx
Labels: VERSION: upcoming major

#7038 fix(core): add keys to jsxnodes when needed
  packages/qwik/src/core/tests/use-styles.spec.tsx
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_mutable_children.snap
  packages/qwik/src/optimizer/core/src/transform.rs
  packages/qwik/src/testing/vdom-diff.unit-util.ts
Labels: VERSION: upcoming major

#6963 perf(serdes): vnode tree shaking
  packages/docs/src/routes/api/qwik-testing/api.json
  packages/docs/src/routes/api/qwik-testing/index.md
  packages/qwik/src/core/api.md
  packages/qwik/src/core/client/dom-container.ts
  packages/qwik/src/core/client/process-vnode-data.unit.tsx
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/shared/shared-container.ts
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/shared/shared-serialization.unit.ts
  packages/qwik/src/core/signal/signal-utils.ts
  packages/qwik/src/core/ssr/ssr-render-jsx.ts
  packages/qwik/src/core/ssr/ssr-types.ts
  packages/qwik/src/core/tests/README.spec.tsx
  packages/qwik/src/core/tests/attributes.spec.tsx
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/core/tests/container.spec.tsx
  packages/qwik/src/core/tests/inline-component.spec.tsx
  packages/qwik/src/core/tests/optimizer-output.spec.tsx
  packages/qwik/src/core/tests/projection.spec.tsx
  packages/qwik/src/core/tests/render-api.spec.tsx
  packages/qwik/src/core/tests/render-namespace.spec.tsx
  packages/qwik/src/core/tests/render-regression.spec.tsx
  packages/qwik/src/core/tests/render-styles.spec.tsx
  packages/qwik/src/core/tests/ssr-render.spec.tsx
  packages/qwik/src/core/tests/use-computed.spec.tsx
  packages/qwik/src/core/tests/use-context.spec.tsx
  packages/qwik/src/core/tests/use-on.spec.tsx
  packages/qwik/src/core/tests/use-resource.spec.tsx
  packages/qwik/src/core/tests/use-sequential-scope.spec.tsx
  packages/qwik/src/core/tests/use-signal.spec.tsx
  packages/qwik/src/core/tests/use-store.spec.tsx
  packages/qwik/src/core/tests/use-styles-scoped.spec.tsx
  packages/qwik/src/core/tests/use-styles.spec.tsx
  packages/qwik/src/core/tests/use-task.spec.tsx
  packages/qwik/src/core/tests/use-visible-task.spec.tsx
  packages/qwik/src/server/ssr-container.ts
  packages/qwik/src/server/ssr-node.ts
  packages/qwik/src/server/vnode-data.ts
  packages/qwik/src/server/vnode-data.unit.tsx
  packages/qwik/src/testing/api.md
  packages/qwik/src/testing/index.ts
  packages/qwik/src/testing/rendering.unit-util.tsx
  packages/qwik/src/testing/vdom-diff.unit-util.ts
  starters/e2e/e2e.attributes.e2e.ts
Labels: VERSION: upcoming major

#7045 chore: make v2 types v1 compatible
  .changeset/fast-baboons-itch.md
  .changeset/rich-wasps-tease.md
  package.json
  packages/docs/check-qwik-build.ts
  packages/docs/src/repl/bundled.tsx
  packages/docs/src/repl/monaco.tsx
  packages/docs/src/repl/worker/repl-messenger.ts
  packages/docs/src/repl/worker/repl-server.ts
  packages/docs/src/routes/api/qwik-testing/api.json
  packages/docs/src/routes/api/qwik-testing/index.md
  packages/docs/src/routes/api/qwik/api.json
  packages/docs/src/routes/api/qwik/index.md
  packages/insights/.eslintignore
  packages/insights/src/components/histogram/index.tsx
  packages/qwik-react/src/react/server-render.tsx
  packages/qwik/package.json
  packages/qwik/public.d.ts
  packages/qwik/server.d.ts
  packages/qwik/src/core/api-extractor.json
  packages/qwik/src/core/api.md
  packages/qwik/src/core/client/dom-render.ts
  packages/qwik/src/core/client/types.ts
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/index.ts
  packages/qwik/src/core/shared/component-execution.ts
  packages/qwik/src/core/shared/jsx/jsx-runtime.ts
  packages/qwik/src/core/shared/jsx/types/jsx-node.ts
  packages/qwik/src/core/shared/prefetch-service-worker/prefetch.ts
  packages/qwik/src/core/shared/scheduler.ts
  packages/qwik/src/core/shared/utils/styles.ts
  packages/qwik/src/core/ssr/ssr-render-jsx.ts
  packages/qwik/src/core/ssr/ssr-types.ts
  packages/qwik/src/core/tests/optimizer-output.spec.tsx
  packages/qwik/src/jsx-runtime.ts
  packages/qwik/src/server/api.md
  packages/qwik/src/server/ssr-container.ts
  packages/qwik/src/server/types.ts
  packages/qwik/src/testing/api.md
  packages/qwik/src/testing/rendering.unit-util.tsx
  packages/qwik/src/testing/vdom-diff.unit-util.ts
  scripts/binding-platform.ts
  starters/apps/e2e/src/components/render/render.tsx
  starters/apps/e2e/src/components/streaming/demo.tsx
  starters/apps/e2e/src/components/streaming/streaming.tsx
Labels: VERSION: upcoming major

#7098 chore(v2 starter): add missing import
  starters/apps/base/src/entry.preview.tsx
Labels: COMP: starters

#7106 fix: serialization of an array of element refs
  .changeset/calm-cycles-know.md
  packages/docs/src/routes/api/qwik/api.json
  packages/qwik/src/core/api.md
  packages/qwik/src/core/shared/qrl/qrl.unit.ts
  packages/qwik/src/core/shared/shared-container.ts
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/shared/shared-serialization.unit.ts
  packages/qwik/src/core/shared/types.ts
  packages/qwik/src/core/tests/ref.spec.tsx
  packages/qwik/src/server/ssr-container.ts
  packages/qwik/src/server/ssr-node.ts
Labels: VERSION: upcoming major
