Repository QwikDev/qwik, pull requests merged in 2024-05, with the labels that each got.

#5238 feat: When closing over values in `server$` the values should be marked as readonly
  packages/qwik-city/runtime/src/server-functions.ts
Labels: COMP: qwik-city, STATUS-2: PR waiting for review

#6303 docs: Document exposing gtag for custom events in Qwik Partytown setup
  packages/docs/src/routes/docs/integrations/partytown/index.mdx
Labels: STATUS-2: PR waiting for review

#6327 fix(qwik-city): Removed artificial recursive limiter from recursive path matching
  packages/qwik-city/runtime/src/route-matcher.ts
  packages/qwik-city/runtime/src/route-matcher.unit.ts
Labels: STATUS-2: PR waiting for review

#6318 fix(image-size-runtime.html): exclude SVG images from Perf: properly …
  packages/qwik/src/optimizer/src/plugins/image-size-runtime.html
Labels: STATUS-2: needs reproduction
