Repository QwikDev/qwik, pull requests merged in 2025-01, with the labels that each got.

#7214 feat: add Qwik articles
  .changeset/warm-tools-tickle.md
  packages/docs/src/components/footer/footer.tsx
  packages/docs/src/components/header/header.tsx
  packages/docs/src/components/svgs/bluesky-logo.tsx
  packages/docs/src/components/svgs/discord-logo.tsx
  packages/docs/src/components/svgs/github-logo.tsx
  packages/docs/src/components/svgs/twitter-logo.tsx
  packages/docs/src/routes/(blog)/blog/(articles)/astro-qwik/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/framer-motion-qwik/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/introducing-qwik-starters/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/module-extraction-the-silent-web-revolution/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-1-2-performance-autopilot/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-2-coming-soon/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-and-qwik-city-have-reached-beta/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-city-routing/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-city-server-functions/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-next-leap/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-rc-milestone/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-tasks/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/qwik-v1/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/resumable-react-how-to-use-react-inside-qwik/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/the-qase-for-qwik-love-at-first-tti/index.mdx
  packages/docs/src/routes/(blog)/blog/(articles)/type-safe-forms-in-qwik/index.mdx
  packages/docs/src/routes/(blog)/blog/components/articles-grid.tsx
  packages/docs/src/routes/(blog)/blog/components/featured-article.tsx
  packages/docs/src/routes/(blog)/blog/components/mdx/article-block.tsx
  packages/docs/src/routes/(blog)/blog/components/mdx/article-block/article-block.tsx
  packages/docs/src/routes/(blog)/blog/components/mdx/article-hero.tsx
  packages/docs/src/routes/(blog)/blog/components/mdx/discord-link.tsx
  packages/docs/src/routes/(blog)/blog/components/newsletter.tsx
  packages/docs/src/routes/(blog)/blog/index.tsx
  packages/docs/src/routes/(blog)/data.ts
  packages/docs/src/routes/(blog)/layout.tsx
Labels: COMP: docs

#7085 fix: const/var props in loops/functions
  .changeset/afraid-bags-jam.md
  .changeset/shaggy-poems-return.md
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/core/tests/inline-component.spec.tsx
  packages/qwik/src/core/tests/use-context.spec.tsx
  packages/qwik/src/core/tests/use-lexical-scope.spec.tsx
  packages/qwik/src/core/tests/use-resource.spec.tsx
  packages/qwik/src/core/tests/use-store.spec.tsx
  packages/qwik/src/core/use/use-resource.ts
  packages/qwik/src/optimizer/core/benches/transform.rs
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_expr_stmt.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_component_with_event_listeners_inside_loop.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_functional_component_2.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_functional_component_capture_props.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__issue_5008.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_wrap_inner_inline_component_prop.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
Labels: VERSION: upcoming major

#7221 chore: remove shop
  .changeset/fluffy-tools-do.md
  packages/docs/src/components/header/header.tsx
  packages/docs/src/routes/(shop)/layout.tsx
  packages/docs/src/routes/(shop)/mutation.ts
  packages/docs/src/routes/(shop)/query.ts
  packages/docs/src/routes/(shop)/shop.css
  packages/docs/src/routes/(shop)/shop/index.tsx
  packages/docs/src/routes/(shop)/shop/shop-cart-rows.tsx
  packages/docs/src/routes/(shop)/shop/shop-cart.tsx
  packages/docs/src/routes/(shop)/shop/shop-header.tsx
  packages/docs/src/routes/(shop)/shop/shop-icon.tsx
  packages/docs/src/routes/(shop)/shop/shop-product.tsx
  packages/docs/src/routes/(shop)/types.d.ts
  packages/docs/src/routes/(shop)/utils.ts
Labels: COMP: docs

#7204 fix: finding context parent and sorting projections in the scheduler
  .changeset/loud-dolphins-relate.md
  packages/qwik/src/core/client/dom-container.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/client/vnode.unit.tsx
  packages/qwik/src/core/shared/scheduler.ts
  packages/qwik/src/core/tests/use-context.spec.tsx
Labels: VERSION: upcoming major

#7225 docs: grammatical error correction
  packages/docs/src/routes/docs/(qwikcity)/advanced/complex-forms/index.mdx
Labels: COMP: docs

#7229 docs: fix up typo
  packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
Labels: COMP: docs

#7228 fix: store effects cleanup & projection siblings serialization
  .changeset/forty-garlics-train.md
  .changeset/friendly-sloths-return.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/signal/signal-subscriber.ts
  packages/qwik/src/core/signal/signal.ts
  packages/qwik/src/core/signal/store.ts
  packages/qwik/src/core/tests/projection.spec.tsx
  packages/qwik/src/core/tests/use-resource.spec.tsx
  packages/qwik/src/core/tests/use-store.spec.tsx
  packages/qwik/src/core/tests/use-styles-scoped.spec.tsx
  packages/qwik/src/core/use/use-resource.ts
  packages/qwik/src/core/use/use-task.ts
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7234 fix: find correct context after rendering empty array
  .changeset/purple-melons-invent.md
  packages/qwik/src/core/tests/use-context.spec.tsx
  packages/qwik/src/server/ssr-node.ts
Labels: VERSION: upcoming major

#7241 chore(starter): update vanilla-extract import
  starters/features/styled-vanilla-extract/package.json
Labels: COMP: starters

#7243 fix: wait for QRL to resolve for signal attribute
  .changeset/silly-nails-own.md
  packages/qwik/src/core/use/use-core.ts
  starters/apps/e2e/src/components/attributes/attributes.e2e.tsx
  starters/apps/e2e/src/components/attributes/attributes.tsx
  starters/e2e/e2e.attributes.e2e.ts
Labels: VERSION: upcoming major

#7182 fix: input's value is string when passing number
  .changeset/neat-maps-tickle.md
  packages/docs/src/routes/docs/(qwik)/components/rendering/index.mdx
  packages/qwik/src/core/shared/jsx/types/jsx-generated.ts
  packages/qwik/src/core/tests/use-signal.spec.tsx
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_input_bind.snap
  packages/qwik/src/optimizer/core/src/transform.rs
Labels: VERSION: upcoming major

#7217 fix: convert destructured array's props to signal
  .changeset/unlucky-dodos-grab.md
  packages/qwik/src/core/shared/platform/platform.ts
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_wrap_prop_from_destructured_array.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
Labels: VERSION: upcoming major

#7259 fix: retry vnode diffing on promise throw
  .changeset/slimy-weeks-hope.md
  packages/qwik/src/core/shared/scheduler.ts
  packages/qwik/src/core/shared/utils/promises.ts
  packages/qwik/src/core/signal/signal-subscriber.ts
  packages/qwik/src/core/tests/render-promise.spec.tsx
  starters/apps/e2e/src/components/attributes/attributes.e2e.tsx
  starters/apps/e2e/src/components/attributes/attributes.tsx
  starters/e2e/e2e.attributes.e2e.ts
Labels: VERSION: upcoming major

#7265 fix: component props as var props
  .changeset/fuzzy-jobs-compare.md
  packages/qwik/src/core/tests/use-store.spec.tsx
  packages/qwik/src/optimizer/core/src/inlined_fn.rs
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_colon_props.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_colon_props3.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_block_stmt.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_block_stmt2.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_expr_stmt.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_component_with_event_listeners_inside_loop.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_children.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_div.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_getter_generation.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_issue_33443.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_mutable_children.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_wrapping.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_wrapping2.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_destructure_args.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_mark_props_as_var_props_for_inner_cmp.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_wrap_object_with_fn_signal.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
Labels: VERSION: upcoming major

#7236 feat: log a warning instead of throwing an error for server host mismatch error
  .changeset/shaggy-poems-appear.md
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/client/vnode.unit.tsx
  packages/qwik/src/core/shared/error/error.ts
  packages/qwik/src/core/shared/scheduler-document-position.spec.ts
  packages/qwik/src/core/shared/scheduler-document-position.ts
  packages/qwik/src/core/shared/scheduler.ts
Labels: VERSION: upcoming major

#7272 chore: cleanup and docs fixes
  packages/docs/package.json
  packages/docs/src/repl/repl-output-update.ts
  packages/qwik/src/core/shared/shared-serialization.unit.ts
  packages/qwik/src/optimizer/core/src/inlined_fn.rs
  pnpm-lock.yaml
Labels: VERSION: upcoming major

#7278 Fix vNode serialization issue on server$
  .changeset/sharp-apples-relate.md
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/use/use-core.ts
  starters/apps/qwikrouter-test/src/routes/issue7260/index.tsx
  starters/e2e/qwikrouter/server.e2e.ts
Labels: VERSION: upcoming major

#7284 fix: don't wrap and serialize functions that are attribute values
  .changeset/six-games-float.md
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_not_wrap_fn.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
Labels: VERSION: upcoming major

#7285 fix: null or undefined as ref attribute value
  .changeset/few-mugs-accept.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/tests/ref.spec.tsx
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7289 Expose missing types & fix package.json internal expose uri
  .changeset/warm-camels-remain.md
  packages/qwik/package.json
  packages/qwik/public.d.ts
Labels: VERSION: upcoming major

#7250 fix: the useOn hook not working with Slot
  .changeset/old-mayflies-fetch.md
  packages/qwik/src/core/shared/component-execution.ts
  packages/qwik/src/core/ssr/ssr-render-jsx.ts
  packages/qwik/src/core/tests/use-on.spec.tsx
Labels: VERSION: upcoming major

#7292 fix: different component rendering with the same key
  .changeset/itchy-comics-develop.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/tests/component.spec.tsx
Labels: VERSION: upcoming major

#7288 fix(starters): improve drizzle integration
  .changeset/forty-bats-rule.md
  starters/features/drizzle/drizzle.config.ts
  starters/features/drizzle/drizzle/schema.ts
  starters/features/drizzle/package.json
Labels: COMP: starters
