Repository QwikDev/qwik, pull requests merged in 2025-03, with the labels that each got.

#7381 chore: cleanup and fix types
  packages/qwik/src/core/client/types.ts
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/debug.ts
  packages/qwik/src/core/shared/component.public.ts
  packages/qwik/src/core/shared/jsx/jsx-runtime.ts
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/shared/types.ts
  packages/qwik/src/core/shared/utils/promises.ts
  packages/qwik/src/core/shared/utils/serialize-utils.ts
  packages/qwik/src/core/use/use-core.ts
  packages/qwik/src/core/use/use-resource.ts
  packages/qwik/src/core/use/use-task.ts
Labels: VERSION: upcoming major

#7390 fix: don't wrap template literals with a function call inside in a si…
  .changeset/chilly-fans-shave.md
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_mark_props_as_var_props_for_inner_cmp.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_not_wrap_var_template_string.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
Labels: VERSION: upcoming major

#7398 chore(starters): correct Auth optimizeDeps instructions
  starters/features/auth/package.json
Labels: COMP: starters

#7410 fix: finding vnodes on interaction
  .changeset/proud-kangaroos-boil.md
  packages/qwik/src/core/client/vnode.ts
Labels: VERSION: upcoming major

#7419 fix: attribute diffing
  .changeset/friendly-beers-heal.md
  .gitignore
  package.json
  packages/insights/package.json
  packages/qwik/package.json
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode-diff.unit.tsx
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/shared/shared-serialization.unit.ts
  packages/qwik/src/core/tests/container.spec.tsx
  packages/qwik/src/testing/vdom-diff.unit-util.ts
  pnpm-lock.yaml
Labels: VERSION: upcoming major

#7427 chore: toMatchDOM fix and refactor
  packages/docs/src/routes/api/qwik-testing/api.json
  packages/docs/src/routes/api/qwik-testing/index.md
  packages/qwik/src/core/client/process-vnode-data.unit.tsx
  packages/qwik/src/core/client/vnode-diff.unit.tsx
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/tests/attributes.spec.tsx
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/core/tests/projection.spec.tsx
  packages/qwik/src/core/tests/render-namespace.spec.tsx
  packages/qwik/src/core/tests/ssr-render.spec.tsx
  packages/qwik/src/testing/api.md
  packages/qwik/src/testing/html.ts
  packages/qwik/src/testing/jsx.ts
  packages/qwik/src/testing/vdom-diff.unit-util.ts
Labels: VERSION: upcoming major

#7430 fix: removing text node from shared text node
  .changeset/wicked-pets-chew.md
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/client/vnode.unit.tsx
Labels: VERSION: upcoming major

#7434 fix(docs): fix up minor typos
  packages/docs/src/routes/docs/(qwikcity)/advanced/request-handling/index.mdx
Labels: COMP: docs

#7432 fix: change client side generated ID to start with build base
  .changeset/fair-cameras-boil.md
  packages/qwik/src/core/api.md
  packages/qwik/src/core/client/dom-container.ts
  packages/qwik/src/core/client/types.ts
  packages/qwik/src/core/shared/shared-container.ts
  packages/qwik/src/core/shared/types.ts
  packages/qwik/src/core/ssr/ssr-types.ts
  packages/qwik/src/core/tests/use-id.spec.tsx
  packages/qwik/src/core/use/use-id.ts
  packages/qwik/src/server/prefetch-implementation.ts
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7446 fix: inserting new node edge case and creating error overlay
  .changeset/cyan-bottles-speak.md
  .changeset/tame-glasses-explain.md
  packages/qwik/src/core/client/dom-container.ts
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/client/vnode.unit.tsx
  packages/qwik/src/core/tests/error-handling.spec.tsx
Labels: VERSION: upcoming major

#7460 docs: update ecosystem style
  packages/docs/src/routes/(ecosystem)/ecosystem.css
  packages/docs/src/routes/(ecosystem)/ecosystem/index.tsx
Labels: COMP: docs
