Repository QwikDev/qwik, pull requests merged in 2025-08, with the labels that each got.

#7778 docs: fix up repl issue 🥗
  packages/docs/src/repl/repl.tsx
Labels: COMP: docs

#7810 fix: handle falsy value for dangerouslySetInnerHTML
  .changeset/tasty-turkeys-stand.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7809 fix: reactivity after spreading props
  .changeset/solid-olives-know.md
  packages/qwik/src/core/internal.ts
  packages/qwik/src/core/qwik.core.api.md
  packages/qwik/src/core/shared/jsx/jsx-runtime.ts
  packages/qwik/src/core/tests/attributes.spec.tsx
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/core/tests/use-task.spec.tsx
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_jsx.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_spread_jsx.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_destructure_args.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop2.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop3.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop4.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop5.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
  packages/qwik/src/optimizer/core/src/words.rs
  starters/e2e/e2e.render.e2e.ts
Labels: VERSION: upcoming major

#7851 docs: fix middleware example 🍿
  packages/docs/src/routes/demo/qwikcity/middleware/layout.tsx
Labels: COMP: docs

#7858 fix(starter): fix up vscode settings merge 🐼
  .changeset/heavy-windows-mate.md
  packages/qwik/package.json
  packages/qwik/src/cli/add/update-files.ts
  packages/qwik/src/cli/add/update-files.unit.ts
  pnpm-lock.yaml
Labels: COMP: starters

#7877 docs: add img tag onLoad cookbook 📌
  packages/docs/src/routes/demo/cookbook/detect-img-tag-onload/index.tsx
  packages/docs/src/routes/docs/cookbook/detect-img-tag-onload/index.mdx
  packages/docs/src/routes/docs/cookbook/index.mdx
  packages/docs/src/routes/docs/menu.md
Labels: COMP: docs

#7876 feat: expose loading and error fields of async computed signal
  .changeset/mean-tires-cover.md
  packages/docs/src/routes/api/qwik/api.json
  packages/docs/src/routes/api/qwik/index.mdx
  packages/qwik/src/core/qwik.core.api.md
  packages/qwik/src/core/reactive-primitives/signal.public.ts
  packages/qwik/src/core/tests/use-async-computed.spec.tsx
  packages/qwik/src/testing/rendering.unit-util.tsx
Labels: VERSION: upcoming major

#7879 chore: update rust version
  Cargo.lock
  packages/qwik/src/optimizer/core/src/add_side_effect.rs
  packages/qwik/src/optimizer/core/src/code_move.rs
  packages/qwik/src/optimizer/core/src/collector.rs
  packages/qwik/src/optimizer/core/src/entry_strategy.rs
  packages/qwik/src/optimizer/core/src/filter_exports.rs
  packages/qwik/src/optimizer/core/src/inlined_fn.rs
  packages/qwik/src/optimizer/core/src/lib.rs
  packages/qwik/src/optimizer/core/src/parse.rs
  packages/qwik/src/optimizer/core/src/props_destructuring.rs
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_custom_inlined_functions.snap
  packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_invalid_segment_expr1.snap
  packages/qwik/src/optimizer/core/src/test.rs
  packages/qwik/src/optimizer/core/src/transform.rs
  packages/qwik/src/optimizer/core/src/utils.rs
  packages/qwik/src/optimizer/core/src/words.rs
  packages/qwik/src/wasm/Cargo.toml
  packages/qwik/src/wasm/src/lib.rs
  rust-toolchain
Labels: VERSION: upcoming major

#7886 fix: finding parent dom element from projected content
  .changeset/shy-shirts-glow.md
  packages/qwik/src/core/client/dom-container.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/tests/projection.spec.tsx
Labels: VERSION: upcoming major

#7885 docs: add GitHub Pages deployment 🐺
  e2e/docs-e2e/tests/Docs/deployments-pages-load.spec.ts
  packages/docs/src/routes/docs/deployments/github-pages/index.mdx
  packages/docs/src/routes/docs/menu.md
Labels: COMP: docs

#7894 docs: update import.meta.glob with eager false 🍒
  packages/docs/src/routes/demo/cookbook/glob-import/index.tsx
  packages/docs/src/routes/docs/cookbook/glob-import/index.mdx
Labels: COMP: docs
