Repository QwikDev/qwik, pull requests merged in 2025-07, with the labels that each got.

#7706 fix: adding popstate and scroll event for SPA navigation
  .changeset/better-shrimps-sin.md
  packages/qwik-router/src/runtime/src/spa-init.ts
  packages/qwik/src/core/tests/render-api.spec.tsx
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7704 fix: nested not serialized loaders
  .changeset/smooth-cups-press.md
  packages/qwik-router/src/middleware/request-handler/middleware.request-handler.api.md
  packages/qwik-router/src/middleware/request-handler/request-event.ts
  packages/qwik-router/src/middleware/request-handler/resolve-request-handlers.ts
  starters/apps/qwikrouter-test/src/routes/loaders-serialization/index.tsx
  starters/e2e/qwikrouter/loaders.e2e.ts
Labels: VERSION: upcoming major

#7705 fix: render SVG attributes with correct namespace
  .changeset/open-beds-grab.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/client/vnode-namespace.ts
  packages/qwik/src/core/shared/utils/markers.ts
  packages/qwik/src/core/tests/render-namespace.spec.tsx
Labels: VERSION: upcoming major

#7674 Docs: Azion Platform Deployment
  packages/docs/public/ecosystem/azion.svg
  packages/docs/src/routes/(ecosystem)/ecosystem.json
  packages/docs/src/routes/docs/deployments/azion/index.mdx
  packages/docs/src/routes/docs/menu.md
Labels: COMP: docs

#7741 docs: update link to qwik-specefic instructions
  packages/docs/src/routes/docs/integrations/i18n/index.mdx
Labels: COMP: docs

#7713 fix(view-transition): rename qwik-router-spa to qwik-navigation
  .changeset/angry-boats-lose.md
  packages/docs/src/routes/docs/cookbook/view-transition/index.mdx
  packages/qwik-router/src/runtime/src/qwik-router-component.tsx
Labels: VERSION: upcoming major

#7746 fix: use on events for headless components
  .changeset/tiny-cows-pick.md
  packages/qwik/src/core/shared/component-execution.ts
  packages/qwik/src/core/shared/utils/types.ts
  packages/qwik/src/core/tests/use-on.spec.tsx
  packages/qwik/src/core/tests/use-visible-task.spec.tsx
Labels: VERSION: upcoming major

#7617 fix: fix up compatibility with a Qwik typescript version
  .changeset/social-kings-visit.md
  starters/features/localize/package.json
Labels: COMP: starters
