Repository QwikDev/qwik, pull requests merged in 2025-05, with the labels that each got.

#7552 feat: allow async operations in useComputed$ hook
  .changeset/good-tables-rush.md
  packages/docs/src/routes/api/qwik/api.json
  packages/docs/src/routes/api/qwik/index.md
  packages/qwik/src/core/core.api.md
  packages/qwik/src/core/index.ts
  packages/qwik/src/core/reactive-primitives/impl/computed-signal-impl.ts
  packages/qwik/src/core/shared/error/error.ts
  packages/qwik/src/core/ssr/ssr-render-jsx.ts
  packages/qwik/src/core/tests/use-computed.spec.tsx
  packages/qwik/src/core/use/use-computed.ts
Labels: VERSION: upcoming major

#7573 fix: eslint 9 config
  eslint.config.mjs
  packages/docs/src/routes/devtools/json/json.ts
  packages/qwik/eslint.config.mjs
  packages/qwik/src/core/preloader/index.ts
  packages/qwik/src/insights/vite/insights-plugin.ts
  packages/qwik/src/server/.eslintrc.cjs
  packages/qwik/src/server/prefetch-strategy.ts
  packages/qwik/src/server/preload-impl.ts
  packages/qwik/src/server/qwik-copy.ts
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7580 chore: update changesets version
  package.json
  pnpm-lock.yaml
Labels: VERSION: upcoming major

#7574 fix: infinity loop while tracking element ref
  .changeset/cold-moons-follow.md
  packages/qwik/src/core/tests/ref.spec.tsx
  packages/qwik/src/server/qwik-types.ts
  packages/qwik/src/server/ssr-container.ts
Labels: VERSION: upcoming major

#7559 docs: make logo adapt to light and dark mode
  .github/assets/qwik-logo.svg
  README.md
  packages/docs/public/logos/qwik-logo.svg
  packages/docs/public/logos/qwik.svg
Labels: COMP: docs

#7588 feat(docs): add vnode tree & state to html tab
  packages/docs/src/components/code-block/code-block.tsx
  packages/docs/src/repl/repl-output-panel.tsx
  packages/docs/src/repl/repl-output-segments.tsx
  packages/docs/src/repl/repl-output-update.ts
  packages/docs/src/repl/repl.css
  packages/docs/src/repl/repl.tsx
  packages/docs/src/repl/types.ts
  packages/docs/src/repl/worker/app-ssr-html.ts
  packages/docs/src/repl/worker/app-update.ts
  packages/qwik/src/core/client/vnode.ts
  packages/qwik/src/core/internal.ts
  packages/qwik/src/core/qwik.core.api.md
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/shared/types.ts
Labels: VERSION: upcoming major

#7621 feat: throw on serializing function
  .changeset/rare-candies-join.md
  packages/qwik/src/core/shared/error/error.ts
  packages/qwik/src/core/shared/shared-serialization.ts
  packages/qwik/src/core/shared/shared-serialization.unit.ts
  packages/qwik/src/core/shared/utils/serialize-utils.ts
Labels: VERSION: upcoming major

#7562 Support rewrite request (Similarly to redirect)
  .changeset/dirty-dolls-heal.md
  packages/docs/src/routes/api/qwik-city-middleware-request-handler/api.json
  packages/docs/src/routes/api/qwik-city-middleware-request-handler/index.mdx
  packages/docs/src/routes/api/qwik-optimizer/api.json
  packages/docs/src/routes/api/qwik-optimizer/index.mdx
  packages/docs/src/routes/docs/(qwikcity)/guides/rewrites/index.mdx
  packages/qwik-city/src/buildtime/vite/dev-server.ts
  packages/qwik-city/src/middleware/request-handler/index.ts
  packages/qwik-city/src/middleware/request-handler/middleware.request-handler.api.md
  packages/qwik-city/src/middleware/request-handler/request-event.ts
  packages/qwik-city/src/middleware/request-handler/request-handler.ts
  packages/qwik-city/src/middleware/request-handler/resolve-request-handlers.ts
  packages/qwik-city/src/middleware/request-handler/response-page.ts
  packages/qwik-city/src/middleware/request-handler/rewrite-handler.ts
  packages/qwik-city/src/middleware/request-handler/types.ts
  packages/qwik-city/src/middleware/request-handler/user-response.ts
  packages/qwik-city/src/runtime/src/qwik-city-component.tsx
  packages/qwik-city/src/runtime/src/types.ts
  packages/qwik/src/optimizer/src/plugins/plugin.ts
  packages/qwik/src/optimizer/src/qwik.optimizer.api.md
  starters/apps/qwikcity-test/src/routes/(common)/products/[id]/index.tsx
  starters/dev-server.ts
  starters/e2e/qwikcity/page.spec.ts
  starters/e2e/qwikcity/util.ts
Labels: COMP: qwik-city, VERSION: upcoming minor

#7631 fix: ensure components are only rendered when necessary
  .changeset/pretty-trees-check.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/tests/component.spec.tsx
Labels: VERSION: upcoming major

#7633 fix: proper empty props diffing
  .changeset/cold-rice-slide.md
  packages/qwik/src/core/client/vnode-diff.ts
  packages/qwik/src/core/tests/component.spec.tsx
Labels: VERSION: upcoming major

#7629 feat: update to latest partytown version
  README.md
  package.json
  packages/create-qwik/README.md
  packages/docs/package.json
  packages/docs/src/components/router-head/vendor.tsx
  packages/docs/src/routes/(blog)/blog/(articles)/introducing-qwik-starters/index.mdx
  packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx
  packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx
  packages/docs/src/routes/docs/integrations/partytown/index.mdx
  packages/docs/vite.config.mts
  packages/qwik-auth/README.md
  packages/qwik-city/README.md
  packages/qwik-labs/README.md
  packages/qwik-react/README.md
  pnpm-lock.yaml
  starters/apps/library/README.md
  starters/apps/starter-partytown-test/package.json
  starters/apps/starter-partytown-test/src/components/app/app.tsx
  starters/apps/starter-partytown-test/src/root.tsx
  starters/features/partytown/package.json
  starters/features/partytown/src/components/partytown/partytown.tsx
Labels: COMP: docs, COMP: starters

#7637 fix: don't wrap static objects with signal
  .changeset/olive-yaks-prove.md
  packages/qwik/src/core/reactive-primitives/internal-api.ts
  packages/qwik/src/core/shared/shared-serialization.unit.ts
  packages/qwik/src/core/tests/component.spec.tsx
  packages/qwik/src/core/tests/inline-component.spec.tsx
  packages/qwik/src/core/tests/projection.spec.tsx
  packages/qwik/src/core/tests/render-namespace.spec.tsx
  packages/qwik/src/core/tests/use-context.spec.tsx
  packages/qwik/src/core/tests/use-store.spec.tsx
Labels: VERSION: upcoming major
